version: '3.5'
services:
  postgres_db:
    container_name: postgres_db
    image: postgres:11.5-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=123123
    ports:
      - 5432:5432
    networks:
      - olist-net

  # adminer:
  #   container_name: adminer
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - olist-net

networks:
  olist-net:
    name: olist-net
    ipam:
      config:
      - subnet: 172.21.0.0/16
